name: CMake Build (Multi-Platform)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y cmake

      - name: Install CMake on macOS
        if: matrix.os == 'macos-latest'
        run: brew install cmake

      - name: Clean build directory (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          if [ -d build ]; then
            rm -rf build
          fi
        shell: bash

      - name: Clean build directory (Windows)
        if: runner.os == 'Windows'
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
        shell: powershell

      - name: Create build directory
        run: cmake -E make_directory build

      - name: Configure with CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Find executable path
        id: find-exe
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            exe_path=$(find build -type f -iname "MinecraftProfileCreator.exe" | head -n 1)
            echo "exe_path=$exe_path" >> $GITHUB_OUTPUT
            echo "os_name=windows" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            app_path=$(find build -type d -iname "MinecraftProfileCreator.app" | head -n 1)
            echo "exe_path=$app_path" >> $GITHUB_OUTPUT
            echo "os_name=mac" >> $GITHUB_OUTPUT
          else
            exe_path=$(find build -type f -iname "MinecraftProfileCreator" | head -n 1)
            echo "exe_path=$exe_path" >> $GITHUB_OUTPUT
            echo "os_name=linux" >> $GITHUB_OUTPUT
          fi
        shell: bash
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftProfileCreator (${{ steps.find-exe.outputs.os_name }})
          path: ${{ steps.find-exe.outputs.exe_path }}

