name: Build and upload executable

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: lukka/get-cmake@v3

      - name: Clean build directory
        if: runner.os != 'Windows'
        run: |
          if [ -d build ]; then
            rm -rf build
          fi
        shell: bash

      - name: Clean build directory (Windows)
        if: runner.os == 'Windows'
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
        shell: powershell

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable-${{ matrix.os }}
          path: ${{ steps.set-output-exe-path.outputs.exe-path }}

      - name: Set output path for artifact upload
        id: set-output-exe-path
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "::set-output name=exe-path::build\\MinecraftProfileCreator.exe"
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            # Assuming app bundle is in build/MinecraftProfileCreator.app
            echo "::set-output name=exe-path::build/MinecraftProfileCreator.app"
          else
            # Linux binary
            echo "::set-output name=exe-path::build/MinecraftProfileCreator"
          fi
        shell: bash
